[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 14
normal.family = "CaskaydiaCove Nerd Font Mono"
normal.style = "Regular"
bold.family = "CaskaydiaCove Nerd Font Mono"
bold.style = "Bold"
italic.family = "CaskaydiaCove Nerd Font Mono"
italic.style = "Italic"
bold_italic.family = "CaskaydiaCove Nerd Font Mono"
bold_italic.style = "Bold Italic"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

[general]
import = [
  "./catppuccin-mocha.toml"
]

